SELECT 'DROP PROCEDURES';
DROP PROCEDURE SINCRONIZAR_HISTORIAL_MAPA;

SELECT 'DROP FUNCTIONS';
DROP FUNCTION LOGIN;

SELECT 'DROP TRIGGERS';
DROP TRIGGER T_CONTENIDO_A;
DROP TRIGGER T_CONTENIDO_M;
DROP TRIGGER T_CONTENIDO_B;
DROP TRIGGER T_GRUPO_M;
DROP TRIGGER T_GRUPO_B;
DROP TRIGGER T_PERMISOS_GRUPOS_A;
DROP TRIGGER T_PERMISOS_GRUPOS_M;
DROP TRIGGER T_PERMISOS_GRUPOS_B;
DROP TRIGGER T_GRUPO_MINIJUEGOS_A;
DROP TRIGGER T_GRUPO_MINIJUEGOS_M;
DROP TRIGGER T_GRUPO_MINIJUEGOS_B;
DROP TRIGGER T_MINIJUEGO_M;
DROP TRIGGER T_MINIJUEGO_B;
DROP TRIGGER T_PERMISOS_MINIJUEGOS_A;
DROP TRIGGER T_PERMISOS_MINIJUEGOS_M;
DROP TRIGGER T_PERMISOS_MINIJUEGOS_B;
DROP TRIGGER T_BOTONES_MAPA_A;
DROP TRIGGER T_BOTONES_MAPA_M;
DROP TRIGGER T_BOTONES_MAPA_B;
DROP TRIGGER T_NINO_A;
DROP TRIGGER T_PREMIO_A;

SELECT 'DROP VIEWS';
DROP VIEW V_CONTENIDO;
DROP VIEW V_GRUPOS;
DROP VIEW V_MINIJUEGOS;
DROP VIEW V_GRUPO_MINIJUEGOS;
DROP VIEW V_HISTORIAL_MAPAS;
DROP VIEW V_FONDO;
DROP VIEW V_MAPA;
DROP VIEW V_BOTONES_MAPA;
DROP VIEW V_PREMIOS;


SELECT 'DROP TABLES';
DROP TABLE TS_FONDO;
DROP TABLE TS_BOTONES_MAPA;
DROP TABLE TS_MAPA;
DROP TABLE TS_CONTENIDO;
DROP TABLE TS_MINIJUEGO;
DROP TABLE TS_GRUPO;
DROP TABLE TS_GRUPO_MINIJUEGOS;
DROP TABLE HISTORIAL_JUEGO;
DROP TABLE HISTORIAL_MAPAS;
DROP TABLE GRUPO_MINIJUEGOS;
DROP TABLE PERMISOS_MINIJUEGOS;
DROP TABLE PERMISOS_GRUPOS;
DROP TABLE BOTONES_MAPA;
DROP TABLE MAPA;
DROP TABLE FONDO;
DROP TABLE GRUPO;
DROP TABLE CONTENIDO;
DROP TABLE MINIJUEGO;
DROP TABLE PREMIOS_USUARIOS;
DROP TABLE PREMIO;
DROP TABLE ANAMNESIS_NINO;
DROP TABLE AUTONOMIA_NINO;
DROP TABLE SOCIALIZACION_NINO;
DROP TABLE LENGUAJE_NINO;
DROP TABLE SESION_NINO;
DROP TABLE NINO;
DROP TABLE LOGOPEDA;
DROP TABLE PERSONAJE;






--mysql --defaults-group-suffix=host1


