CREATE OR REPLACE VIEW V_CONTENIDO AS
	SELECT TSC_ID_CONTENIDO AS ID_CONTENIDO, C_CASTELLANO AS CASTELLANO, C_EUSKERA AS EUSKERA, 
		   C_IMAGEN AS IMAGEN, PG_ID_NINO AS ID_NINO, TSC_ACCION AS ACCION, TSC_FECMOD AS FECMOD
	FROM GRUPO, PERMISOS_GRUPOS, TS_CONTENIDO 
		LEFT JOIN CONTENIDO ON C_ID_CONTENIDO = TSC_ID_CONTENIDO
	WHERE G_ID_GRUPO = PG_ID_GRUPO
	  AND G_CONTENIDO_SOLUCION = C_ID_CONTENIDO OR G_CONTENIDO_OPCION = C_ID_CONTENIDO;


CREATE OR REPLACE VIEW V_GRUPOS AS
	SELECT TSG_ID_GRUPO AS ID_GRUPO, TSG_CONTENIDO_SOLUCION AS SOLUCION, TSG_CONTENIDO_OPCION AS OPCION, TSG_ID_NINO AS ID_NINO, TSG_ACCION AS ACCION, TSG_FECMOD AS FECMOD
	FROM TS_GRUPO;


CREATE OR REPLACE VIEW V_MINIJUEGOS AS
	SELECT TSM_ID_MINIJUEGO AS ID_MINIJUEGO, M_NOMBRE AS NOMBRE, M_DESCRIPCION AS DESCRIPCION, PM_MAXIMO AS MAXIMO, PM_MINIMO AS MINIMO, PM_PUNTUACION_MAXIMA AS PUNTUACION_MAXIMA, 
			TSM_ID_NINO AS ID_NINO, TSM_ACCION AS ACCION, TSM_FECMOD AS FECMOD
	FROM TS_MINIJUEGO
		LEFT JOIN PERMISOS_MINIJUEGOS ON TSM_ID_MINIJUEGO = PM_ID_MINIJUEGO AND PM_ID_NINO = TSM_ID_NINO
		LEFT JOIN MINIJUEGO ON M_ID_MINIJUEGO = TSM_ID_MINIJUEGO;


CREATE OR REPLACE VIEW V_GRUPO_MINIJUEGOS AS
	SELECT TSGM_ID_MINIJUEGO AS ID_MINIJUEGO, TSGM_ID_GRUPO AS ID_GRUPO, TSGM_ACCION AS ACCION, TSGM_FECMOD AS FECMOD
	FROM TS_GRUPO_MINIJUEGOS 
		LEFT JOIN GRUPO_MINIJUEGOS ON GM_ID_MINIJUEGO = TSGM_ID_MINIJUEGO AND GM_ID_GRUPO = TSGM_ID_GRUPO;

CREATE VIEW V_FONDO AS
	SELECT TSF_ID_FONDO AS ID_FONDO, F_IMAGEN AS IMAGEN, TSF_ACCION AS ACCION, TSF_FECMOD AS FECMOD
	FROM TS_FONDO 
		LEFT JOIN FONDO ON TSF_ID_FONDO = F_ID_FONDO;

CREATE VIEW V_MAPA AS
	SELECT TSMA_ID_MAPA AS ID_MAPA, MA_NOMBRE AS NOMBRE, MA_IMAGEN AS IMAGEN, TSMA_ACCION AS ACCION, TSMA_FECMOD AS FECMOD
	FROM TS_MAPA 
		LEFT JOIN MAPA ON TSMA_ID_MAPA = MA_ID_MAPA;

CREATE VIEW V_BOTONES_MAPA AS
	SELECT TSBM_ID_MAPA AS ID_MAPA, TSBM_ID_BOTON AS ID_BOTON, BM_POSICION_X AS POSICION_X, BM_POSICION_Y AS POSICION_Y, BM_WIDTH AS WIDTH, BM_HEIGHT AS HEIGHT, TSBM_ACCION AS ACCION, TSBM_FECMOD AS FECMOD
	FROM TS_BOTONES_MAPA 
		LEFT JOIN BOTONES_MAPA ON TSBM_ID_MAPA = BM_ID_MAPA AND TSBM_ID_BOTON = BM_ID_BOTON;

CREATE VIEW V_PREMIOS AS
	SELECT PR_ID_PREMIO AS ID_PREMIO, PR_NOMBRE AS NOMBRE, PR_IMAGEN AS IMAGEN, 
		   PU_ID_NINO AS ID_NINO, PU_CONSEGUIDO AS CONSEGUIDO, PU_FECMOD AS FECMOD
	FROM PREMIO, PREMIOS_USUARIOS
	WHERE PU_ID_PREMIO = PR_ID_PREMIO;